# Numpy

In [4]:
import numpy as np

## Array

In [5]:
import numpy as np

a = np.array([1, 2, 3])

In [6]:
a

array([1, 2, 3])

In [7]:
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [10]:
print(np.arange(4))
print(np.arange(0,10,2))

[0 1 2 3]
[0 2 4 6 8]


In [11]:
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

## Add, Remove, and Sort

In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,])

In [15]:
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [16]:
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

## Shape and Size

In [21]:
array_example = np.array([[[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]],
                          
                          [[0, 1, 2, 3],
                          [4, 5, 6, 7]]])
                
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [22]:
array_example.ndim

3

In [23]:
array_example.size

24

In [24]:
array_example.shape

(3, 2, 4)

In [25]:
arr_one = np.array([[1, 2, 3, 4, 5]])

In [26]:
arr_one.ndim

2

In [27]:
arr_one.size

5

In [28]:
arr_one.shape

(1, 5)

## Reshape

In [29]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [30]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [31]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

## Convert 1D to 2D

In [32]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [33]:
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [35]:
row_vector = a[np.newaxis,  :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [37]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [38]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [39]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [40]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

## Indexing and Slicing

In [8]:
import numpy as np

In [9]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [10]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [12]:
five_up = (a >= 5)

print(a[five_up])
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]
[ 5  6  7  8  9 10 11 12]


In [13]:
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [14]:
c = a[(a > 2) & (a < 11)]

print(c)

[ 3  4  5  6  7  8  9 10]


## Creating Array from Existing Data

In [15]:
arr = np.array([ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [16]:
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [22]:
a_1 = np.array([[1, 1],
               [2, 2]])

In [23]:
a_2 = np.array([[3, 3],
               [4, 4]])

In [24]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [25]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [41]:
arrsplit = np.array([[ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
                     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

print(arrsplit)


[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [42]:
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [30]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [32]:
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Basic array operations

In [33]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [34]:
b = np.array([[1, 1], [2, 2]])
b

array([[1, 1],
       [2, 2]])

In [35]:
b.sum(axis=0)

array([3, 3])

In [36]:
b.sum(axis=1)

array([2, 4])

In [37]:
data = np.array([1, 2])
data

array([1, 2])

In [38]:
ones = np.ones(2)
ones

array([1., 1.])

In [39]:
data + ones

array([2., 3.])

In [40]:
data * data

array([1, 4])

In [43]:
data / data

array([1., 1.])

## Broadcasting

In [44]:
data * 1.6

array([1.6, 3.2])

In [45]:
data * 2

array([2, 4])

## More Array Operations

In [47]:
A = np.array([[0.45053314, 0.64572875, 0.82086531, 0.65390389],
             [0.76530923, 0.12986534, 0.63982146, 0.14547893],
             [0.65302142, 0.83271045, 0.56271824, 0.75092316]])

print(A)

[[0.45053314 0.64572875 0.82086531 0.65390389]
 [0.76530923 0.12986534 0.63982146 0.14547893]
 [0.65302142 0.83271045 0.56271824 0.75092316]]


In [48]:
A.sum()

7.05087932

In [49]:
A.min()

0.12986534

In [50]:
A.min(axis=0)

array([0.45053314, 0.12986534, 0.56271824, 0.14547893])

In [51]:
A.max()

0.83271045

In [52]:
A.max(axis=1)

array([0.82086531, 0.76530923, 0.83271045])

In [53]:
A.std()

0.22581842633662538

# Matrices

## Creating Matrices

In [54]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [55]:
np.ones((3,2))
np.zeros((3,2))
np.random.random((3,2))

array([[0.56778528, 0.91917458],
       [0.89079747, 0.7128248 ],
       [0.6890769 , 0.70736072]])

In [56]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.40352285 0.75066309]
 [0.10965347 0.64716452]
 [0.62420231 0.9973704 ]]


## Matrix Arithmetic

In [57]:
data = np.array([[1, 2], [3, 4]])
print(data)

[[1 2]
 [3 4]]


In [58]:
ones = np.ones([2, 2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [59]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [60]:
ones_row = np.ones([ 1, 2])
print(ones_row)

[[1. 1.]]


In [61]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


## Dot Product

In [62]:
a_1 = np.array([[1, 2, 3], [4, 5, 6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7, 8], [9, 10], [11, 12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [63]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

## Matrix Indexing

In [65]:
data = np.array([[1, 2], [3, 4], [5, 6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


## Matrix Aggregation

In [66]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [67]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [68]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


## Transposing and Reshaping

In [69]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [70]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [71]:
data_col = np.array([[1, 2, 3, 4, 5, 6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [72]:
data_col.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
data_col.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [74]:
arr = np.arange(6).reshape((2, 3))
print(arr)

[[0 1 2]
 [3 4 5]]


## N-Dimensial Array

In [75]:
ndarr = np.array([[[1, 2], [3, 4]],
                 [[5, 6], [7, 8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [76]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [77]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [78]:
print(np.random.random((4,3,2)))

[[[0.37921478 0.70408155]
  [0.27958074 0.83777701]
  [0.43967707 0.17429783]]

 [[0.29723559 0.66291837]
  [0.27180486 0.1084343 ]
  [0.60745712 0.77064554]]

 [[0.25366644 0.95450184]
  [0.94549805 0.42096387]
  [0.90186184 0.14537017]]

 [[0.88646192 0.77814701]
  [0.68959188 0.69079989]
  [0.31373697 0.34581079]]]


## Flatten N-Dimensional Array

In [79]:
arrflat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [80]:
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Working with Math Formulas

In [81]:
error = (1/n) * np.sum(np.square(observed - prediction))

NameError: name 'n' is not defined